# permissions for end users to edit freebsdnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freebsdnode-editor-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes/status
  verbs:
  - get
