# permissions for end users to view freebsdnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freebsdnode-viewer-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes/status
  verbs:
  - get
