# permissions for end users to view nodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-viewer-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - nodes/status
  verbs:
  - get
