# permissions for end users to edit poudrierejails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poudrierejail-editor-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierejails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierejails/status
  verbs:
  - get
