# permissions for end users to edit poudriereportstrees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poudriereportstree-editor-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - poudriereportstrees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - poudriereportstrees/status
  verbs:
  - get
