# permissions for end users to view poudrierebulkbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poudrierebulkbuild-viewer-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierebulkbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierebulkbuilds/status
  verbs:
  - get
