---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes/finalizers
  verbs:
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - freebsdnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierebulkbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierebulkbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierebulkbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierejails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierejails/finalizers
  verbs:
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - poudrierejails/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - poudriereportstrees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.znet
  resources:
  - poudriereportstrees/finalizers
  verbs:
  - update
- apiGroups:
  - freebsd.znet
  resources:
  - poudriereportstrees/status
  verbs:
  - get
  - patch
  - update
